### ISSUE TITLE
Cannot style z-index of toast

### ISSUE THREAD

**Issue by ROODAY** [PolymerElements/paper-toast#21]
Changing the z-index within :host does not work. Also, I feel there should be a z-index attribute added to toast so that it can be easier to ensure it remains on top.

**Comment by leodido** [comment]
I would simple use something like

```css
paper-toast {
  z-index: 1;
  ...
}
```

into my custom theme.

But can be I am wrong.
