### ISSUE TITLE
Toast fitInto/fit-bottom not working correctly.

### ISSUE THREAD

**Issue by Boscop** [PolymerElements/paper-toast#94]
When using paper-toast with `class="fit-bottom"`, it has the right width (same as the element assigned to `toast.fitInto`) but it's always aligned to the left edge of the window.
I encountered this in my test project which is based on the [Starter Kit Plus](https://github.com/StartPolymer/polymer-starter-kit-plus).
I added a page with a form with `id="myform"` and this toast:
```html
<paper-toast id="toast" class="fit-bottom"></paper-toast>
```
```css
      #toast {
        --paper-toast-background-color: red;
        --paper-toast-color: white;
      }
```
Then I open it like this:
```js
this.$.toast.fitInto = this.$.myform;
this.$.toast.text = 'Error: ' + err;
this.$.toast.open();
```
The toast has the same width as `myform` but it's aligned to the left of the window, over the drawer.

It looks like this:
![https://i.imgur.com/zs736I7.png](https://i.imgur.com/zs736I7.png)
